from tkinter import* # this * means we are importing all the function widget of tkinter module
import random
from PIL import ImageTk,Image
rootwelcome=Tk()
attempt=10#this is life of player
answer=random.randint(1,100)# answer variable will contain any random number generated by our system
rootwelcome.title("Number Guessing Game v 1.0.0 BY BIO-B")
rootwelcome.configure(background="#d9d650")
rootwelcome.geometry("500x500")
#============ lets make our frames====================frames are just like our photo frames ok!
frame1=LabelFrame(rootwelcome,text="NIBIO-B",fg="blue",width=500,relief="raise")
frame1.pack(side=TOP)
frame2=Frame(rootwelcome,height=100,relief="raise")
frame2.pack(side=BOTTOM)
frame3=LabelFrame(rootwelcome,text="player",fg="green",width=500,relief="raise")
frame3.pack(side=TOP)
#default player==============
playername=StringVar()
playername.set("Nobit Nobi")
#============== now we will make answer checking function==============
def check_answer():
    global attempt
    global text
    global entry_window
    global answer
    global btn_check
    fife2=Frame(rootwelcome,height=100,relief="raise")
    fife2.pack(side=BOTTOM)
    life()
    attempt -=1
    guess=int(entry_window.get())
    if answer==guess:
        text.set(" Congrate!!...  "+playername.get()+ "  You Win ")
        Label(fife2,image=save,bg="#d9d650").pack()
        btn_check.pack_forget()
    elif attempt ==0:
        text.set("You run out of attempts")
        lo=Label(fife2,image=celebrate,bg="#d9d650")
        lo.pack(side=BOTTOM)
        btn_check.pack_forget()
    elif guess<answer:
        text.set("Incorrect! You have "+str(attempt)+" attempts remainig -GO higher!!")
        for r in range(0,attempt,1):
            lw=Label(fife2,image=life_left,bg="#d9d650")
            lw.pack(side=LEFT)
    elif guess>answer:
        text.set("Incorrect! You have "+str(attempt)+" attempts remainig -GO lower!!")
        for r in range(0,attempt,1): 
            lw=Label(fife2,image=life_left,bg="#d9d650")
            lw.pack(side=LEFT)
    return
#===============Game window======================
def gamewindow():
    w=rootwelcome.winfo_screenwidth()
    h=rootwelcome.winfo_screenwidth()
    rootwelcome.geometry("%dx%d+0+0"%(w,h))
    l1=Label(rootwelcome,text="Let's start The Game",fg="white",bg="#d9d650",font=("arial",50,"bold"))
    l1.pack()
    l2=Label(rootwelcome,text="Guess the number bewteen 1 and 100",bg="#d9d650",font=("arial",20,"bold"))
    l2.pack()
    global entry_window
    global btn_check
    global guess_attempt
    global text
    global life_left
    global lw
    global save
    global celebrate
    entry_window=Entry(rootwelcome,width=10,borderwidth=5)
    entry_window.pack()
    btn_check=Button(rootwelcome,text="check",bg="#d9d650",font=("arial",30,"bold"),command=check_answer)
    btn_check.pack()
    
    
    text=StringVar()
    
    text.set("You have 10 attempts remaining! Good luck "+playername.get())
    guess_attempt=Label(rootwelcome,textvariable=text,bg="#d9d650",font=("arial",30,"bold"))
    guess_attempt.pack()
    btn_quit=Button(rootwelcome,text="Quit",fg="red",bg="#d9d650",font=("arial",20,"bold"),command=rootwelcome.destroy)
    btn_quit.pack()
    life_left=PhotoImage(file="heart.png")
    save=PhotoImage(file="save.png")
    celebrate=PhotoImage(file="loser.png")
    lw=Label(rootwelcome,image=life_left,bg="#d9d650")
    lw.pack(side=LEFT)
#===========defing cleaning frames for new messages of game============
def hide_frame1_welcome():
    frame1.destroy()# this will dissaper the frame1
    frame2.destroy()
    frame3.destroy()
    #==============lets call our game window=================
    gamewindow()
#==============lets make our welcome screen==========
welcome_label=Label(frame1,text="Welcome to Number guessing game",fg="white",bg="green",font=("arial",23))
welcome_label.pack()
name_label=Label(frame3,text="Player Name: ",font=("roboto",25,"bold"))
name_label.grid(row=0,column=0)
entry_playername=Entry(frame3,width=30,borderwidth=6,textvariable=playername)
entry_playername.grid(row=0,column=1)
hint_label=Label(frame2,text="solve the Quest for hint"+u":\0001F609",font=(20))
hint_label.pack()
start_button=Button(frame2,text="start game",fg="black",bg="#1ee373",font=("roboto",60,"bold"),command=hide_frame1_welcome)
start_button.pack()











rootwelcome.mainloop()